name: Java CI with Maven

on:
  push:
    branches: ["main", "cicd"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build Java Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCLOUD_CREDS }}'

      - name: Build with Maven
        run: mvn -B package --file project/pom.xml

  run_tests:
    name: Run Unit, API, & Integration Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCLOUD_CREDS }}'

      - name: Run Tests with Maven
        run: mvn clean test --file project/pom.xml

  generate_reports:
    name: Generate PMD, Jacoco, and Checkstyle reports
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle
        working-directory: project
      
      - name: Run Static Analysis (PMD)
        run: mvn pmd:check
        working-directory: project

      - name: Run Branch Coverage with Jacoco
        run: mvn jacoco:report
        working-directory: project

      - name: Copy Reports to Repository
        run: |
          cat project/target/checkstyle-result.xml
          cat project/target/site/jacoco/index.html
          cat project/target/site/pmd.html